Repository sitambhra/Masala-Trails, pull requests merged in 2025-02, with the labels that each got.

#11 Registration pages done.
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: enhancement, JWOC25, Intermediate

#15 Scroll to Top button Added
  package-lock.json
  package.json
  src/App.jsx
Labels: enhancement, JWOC25, medium

#22 contact link done
  src/App.jsx
  src/components/Contact.jsx
Labels: enhancement, JWOC25, Easy

#27 privacy policy page added
  src/App.jsx
  src/components/Privacy.jsx
Labels: JWOC25, medium

#29 Issue#25: Added DarkMode Feature
  package-lock.json
  src/App.jsx
  src/components/About.jsx
  src/components/Contact.jsx
  src/components/DarkMode.jsx
  src/components/Navbar.jsx
  src/pages/Categories.jsx
  src/pages/Home.jsx
  src/pages/Latest.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/pages/Submit.jsx
  src/utils/moon.png
  src/utils/sun.png
  tailwind.config.js
Labels: enhancement, JWOC25, hard

#35 Fix: Footer
  src/App.jsx
  src/components/Footer.jsx
Labels: good first issue, JWOC25, Easy

#36 removed extra darkmode button
  src/components/Navbar.jsx
Labels: JWOC25, Easy

#42 FAQ section done
  src/App.jsx
  src/components/Footer.jsx
  src/pages/Faq.jsx
Labels: enhancement, JWOC25, medium

#43 Icon Redirects to home page
  src/components/Navbar.jsx
Labels: bug, JWOC25, Easy

#46 added emailjs to contact page
  .env
  .gitignore
  package-lock.json
  package.json
  src/components/Contact.jsx
Labels: enhancement, JWOC25, medium

#44 testimonial section added.
  src/App.jsx
  src/assets/chef1.jpeg
  src/assets/man.jpeg
  src/assets/man2.jpeg
  src/assets/woman1.jpeg
  src/assets/woman3.jpeg
  src/pages/Testimonial.jsx
Labels: enhancement, JWOC25, medium

#61 fixed the navbar on top
  src/App.jsx
  src/components/About.jsx
  src/components/Contact.jsx
  src/components/Navbar.jsx
  src/components/Privacy.jsx
  src/pages/Categories.jsx
  src/pages/Faq.jsx
  src/pages/Latest.jsx
  src/pages/Login.jsx
  src/pages/RecipesPage.jsx
  src/pages/Submit.jsx
Labels: medium, JWOC

#80 Issue no #79 [FIXED] Enhance Homepage with Zoom-In Effect on Featured Recipes Card Image and Add Copyright Year in Footer.
  src/components/CopyrightYear.jsx
  src/components/Footer.jsx
  src/components/RecipeCard.jsx
Labels: Easy
